version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "redditsearcher"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rqvudx67p6w9"
s3_prefix = "redditsearcher"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
