AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reddit_comment_searcher

  Sample SAM Template for reddit_comment_searcher

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  RedditCommentSearcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: reddit_searcher/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        RedditCommentSearcher:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /reddit_search
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RedditCommentSearcherApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  RedditCommentSearcherFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RedditCommentSearcherFunction.Arn
  RedditCommentSearcherFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RedditCommentSearcherFunctionRole.Arn
